### ISSUE TITLE
Visual Studio 2019 support

### ISSUE THREAD

**Issue by crystalgreen** [RicoSuter/NuGetReferenceSwitcher#46]
It would be helpful to support the new Visual Studio 2019.

**Comment by RicoSuter** [comment]
Not planned - please use dnt instead: https://github.com/RicoSuter/DNT

**Comment by crystalgreen** [comment]
Okay, thanks for the info.

**Comment by quirijnslings** [comment]
Does DNT work for .NET Framework projects as well? It looks like 'core-only' to me.

**Comment by RicoSuter** [comment]
It should work - it shurely does for SDK-style projects targeting full .net - but I think it should also work for legacy projects...

**Comment by quirijnslings** [comment]
I get an error on all my projects, 'foobar.csproj could not be loaded: Could not locate the tools (MSBuild) path.' Can I create an issue for that?

**Comment by RicoSuter** [comment]
Do you have vs 2017 installed?

**Comment by RicoSuter** [comment]
Vs 2019 not ready yet there too: https://github.com/RicoSuter/DNT/pull/37#issuecomment-486967572

**Comment by quirijnslings** [comment]
Thanks, I will wait for that and in the mean time move back to VS2017 if I need reference switching. Thanks for your help.
